[project]
name = 'ScienceChain-Research-Network'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.peer-review-system]
path = 'contracts/peer-review-system.clar'
clarity_version = 3
epoch = '3.2'

[contracts.replication-tracking-network]
path = 'contracts/replication-tracking-network.clar'
clarity_version = 3
epoch = '3.2'

[contracts.research-data-registry]
path = 'contracts/research-data-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.research-integrity-rewards]
path = 'contracts/research-integrity-rewards.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
